name: tonic_ui_widgetbook
publish_to: none

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  tonic_ui: any
  widgetbook: ^3.8.1
  widgetbook_annotation: ^3.1.0
  accessibility_tools:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  widgetbook_generator: ^3.8.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
